[package]
name = "jobs"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
# Core
tokio.workspace = true
tracing.workspace = true
sqlx.workspace = true

# Domain layer
domain = { path = "../../core/domain" }
